left_allegro_hand_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - left_gripper_joint_00   
      - left_gripper_joint_01
      - left_gripper_joint_02
      - left_gripper_joint_03
      - left_gripper_joint_04
      - left_gripper_joint_05
      - left_gripper_joint_06
      - left_gripper_joint_07
      - left_gripper_joint_08
      - left_gripper_joint_09
      - left_gripper_joint_10
      - left_gripper_joint_11
      - left_gripper_joint_12
      - left_gripper_joint_13
      - left_gripper_joint_14
      - left_gripper_joint_15
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    # === Gains du PID ===
    gains:
      left_gripper_joint_00: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      left_gripper_joint_01: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      left_gripper_joint_02: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      left_gripper_joint_03: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      left_gripper_joint_04: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      left_gripper_joint_05: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      left_gripper_joint_06: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      left_gripper_joint_07: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      left_gripper_joint_08: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      left_gripper_joint_09: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      left_gripper_joint_10: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      left_gripper_joint_11: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      left_gripper_joint_12: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      left_gripper_joint_13: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      left_gripper_joint_14: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      left_gripper_joint_15: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}

right_allegro_hand_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - right_gripper_joint_00   
      - right_gripper_joint_01
      - right_gripper_joint_02
      - right_gripper_joint_03
      - right_gripper_joint_04
      - right_gripper_joint_05
      - right_gripper_joint_06
      - right_gripper_joint_07
      - right_gripper_joint_08
      - right_gripper_joint_09
      - right_gripper_joint_10
      - right_gripper_joint_11
      - right_gripper_joint_12
      - right_gripper_joint_13
      - right_gripper_joint_14
      - right_gripper_joint_15
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    # === Gains du PID ===
    gains:
      right_gripper_joint_00: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      right_gripper_joint_01: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      right_gripper_joint_02: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      right_gripper_joint_03: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      right_gripper_joint_04: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      right_gripper_joint_05: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      right_gripper_joint_06: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      right_gripper_joint_07: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      right_gripper_joint_08: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      right_gripper_joint_09: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      right_gripper_joint_10: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      right_gripper_joint_11: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      right_gripper_joint_12: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      right_gripper_joint_13: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      right_gripper_joint_14: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}
      right_gripper_joint_15: {p: 5.0, i: 0.0, d: 0.2, i_clamp: 1.0}