# MoveIt uses this configuration for controller management

# Scaling factors for velocity and acceleration
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]

joint_limits:
  # Existing joints for the left arm
  left_elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.15
    has_acceleration_limits: true
    max_acceleration: 3.15
    has_effort_limits: true
    max_effort: 150.0
  left_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 3.15
    has_acceleration_limits: true
    max_acceleration: 3.15
    has_effort_limits: true
    max_effort: 150.0
  left_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 3.15
    has_acceleration_limits: true
    max_acceleration: 3.15
    has_effort_limits: true
    max_effort: 150.0
  left_wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: true
    max_acceleration: 3.2
    has_effort_limits: true
    max_effort: 28.0
  left_wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: true
    max_acceleration: 3.2
    has_effort_limits: true
    max_effort: 28.0
  left_wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: true
    max_acceleration: 3.2
    has_effort_limits: true
    max_effort: 28.0
  left_gripper_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0

  # Existing joints for the right arm
  right_elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.15
    has_acceleration_limits: true
    max_acceleration: 3.15
    has_effort_limits: true
    max_effort: 150.0
  right_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 3.15
    has_acceleration_limits: true
    max_acceleration: 3.15
    has_effort_limits: true
    max_effort: 150.0
  right_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 3.15
    has_acceleration_limits: true
    max_acceleration: 3.15
    has_effort_limits: true
    max_effort: 150.0
  right_wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: true
    max_acceleration: 3.2
    has_effort_limits: true
    max_effort: 28.0
  right_wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: true
    max_acceleration: 3.2
    has_effort_limits: true
    max_effort: 28.0
  right_wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: true
    max_acceleration: 3.2
    has_effort_limits: true
    max_effort: 28.0
  right_gripper_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0

  # Allegro gripper joints for the left side
  left_gripper_joint_00:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  left_gripper_joint_01:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  left_gripper_joint_02:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  left_gripper_joint_03:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  left_gripper_joint_04:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  left_gripper_joint_05:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  left_gripper_joint_06:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  left_gripper_joint_07:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  left_gripper_joint_08:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  left_gripper_joint_09:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  left_gripper_joint_10:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  left_gripper_joint_11:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  left_gripper_joint_12:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  left_gripper_joint_13:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  left_gripper_joint_14:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  left_gripper_joint_15:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0

  # Allegro gripper joints for the right side
  right_gripper_joint_00:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  right_gripper_joint_01:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  right_gripper_joint_02:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  right_gripper_joint_03:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  right_gripper_joint_04:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  right_gripper_joint_05:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  right_gripper_joint_06:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  right_gripper_joint_07:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  right_gripper_joint_08:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  right_gripper_joint_09:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  right_gripper_joint_10:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  right_gripper_joint_11:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  right_gripper_joint_12:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  right_gripper_joint_13:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  right_gripper_joint_14:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
  right_gripper_joint_15:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_effort_limits: true
    max_effort: 5.0
